### ISSUE TITLE
github访问不稳定

### ISSUE THREAD

**Issue by mars167** [qutgitstudent/ZhouWeiMyGithubProject#1]
因为运营商网络的原因github时常不能访问甚至ping不通，建议老师使用国内的gitee等托管平台

**Comment by mars167** [comment]
![截屏2020-02-01下午8 36 38](https://user-images.githubusercontent.com/29228178/73592203-b4aadf80-4532-11ea-9793-9f770d339a78.png)

**Comment by qutgitstudent** [comment]
更新到了存在的问题中，在百度云盘中添加了gitee操作的录像
